services:
  database:
    image: postgres:17-alpine
    container_name: database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./src
    container_name: app
    restart: always
    command: sh -c "flask --app run.py db upgrade && python run.py"
    env_file:
      - .env
    volumes:
      - ./src:/app
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy


volumes:
  postgres-data: