"""modificate user model

Revision ID: 3b1ea8abdb5a
Revises: 5e9dde58afc3
Create Date: 2025-10-18 19:55:08.349444

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3b1ea8abdb5a"
down_revision = "5e9dde58afc3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_hash", sa.String(length=128), nullable=False)
        )
        batch_op.alter_column(
            "username",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=64),
            existing_nullable=False,
        )
        batch_op.create_unique_constraint(None, ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "username",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False,
        )
        batch_op.drop_column("password_hash")

    # ### end Alembic commands ###
