"""add recipes

Revision ID: 9b182fd1fab7
Revises: 455d5b18e1b2
Create Date: 2025-10-19 07:32:55.861810

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9b182fd1fab7"
down_revision = "455d5b18e1b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ingredients", sa.Text(), nullable=False))
        batch_op.add_column(sa.Column("instructions", sa.Text(), nullable=False))
        batch_op.add_column(
            sa.Column("image_filename", sa.String(length=300), nullable=True)
        )
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.alter_column(
            "title",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=200),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])
        batch_op.drop_column("discription")
        batch_op.drop_column("cook_time")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cook_time", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "discription",
                sa.VARCHAR(length=500),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "title",
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )
        batch_op.drop_column("user_id")
        batch_op.drop_column("image_filename")
        batch_op.drop_column("instructions")
        batch_op.drop_column("ingredients")
        batch_op.drop_column("description")

    # ### end Alembic commands ###
